// This file can be generated by Terraform
// URLs of workers/pages
export const SITE_BASE_URL = "https://byrdocs.cpphusky.xyz"
export const DATA_BASE_URL = "https://data.byrdocs.cpphusky.xyz"
export const PUBLISH_SITE_BASE_URL = "https://publish.byrdocs.cpphusky.xyz"
export const DEV_SITE_BASE_URL = "https://byrdocs.cpphusky.workers.dev"
// URLs of repositories
export const ARCHIVE_REPO_URL = "https://github.com/byrdocs/byrdocs-archive"
